name: Check Website

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run script
        run: python shifts.py
